### PR TITLE
row_width handling implemented

### PR DESCRIPTION
**Pull request by mikias-abiy**
I've found your module very use full but there was on issue though. I wasn't able to alter the width of the rows. So I implemented it. There is not much change to it to be explained. Don't be frustrated by the number of lined added and removed most of it is just to make it comply with the pep-8 style guide.

### CODE REVIEW

**Comment by kremastra** [comment]
Thank you for your contribution!
I will review this pull request next week.

**Comment by kremastra** [comment]
Please check your changes again.
When testing I get an error "TypeError: 'int' object is not subscriptable" in the try block.
Thank you!

**Comment by mikias-abiy** [comment]
Okay @kremastra  sorry for the inconvenience

**Comment by mikias-abiy** [comment]
I've looked at it and there was an i variable from the past code which i was using for iterating through the data and index the data list. I was only using the button_text_mode == 1 and the variable was only in mode 2 & 3. Any ways I've fixed it i'll create a pull request.

**Comment by kremastra** [comment]
Buddy, the program works, but in the ROW_WIDTH = 1, 2 or 4+ options the visualization of the control buttons breaks.

It is necessary that the three control buttons at the bottom (<---, m/n, --->) are always in the same row.

Need to fix this.

The only option when the visualization is correct is ROW_WIDTH = 3.

image
image
image

**Comment by mikias-abiy** [comment]
i've got a simple fix for that. so when adding navigation keyboard instead of using the add method we need to use row method.
Again sorry for the inconvenience. Just implemented it in my app and only used it with the options row_width=3 and button_text_mode=1.

**Comment by kremastra** [comment]
Yes, using the "row" method fixed the problem for options 1 and 2, thank you!
But for options ROW_WIDTH = 4 and higher the situation is the same.
It is best to add in the README that ROW_WIDTH can take values from 1 to 3 only.

OK, I will add changes to the pull request and release new version soon.
Thank you for your contribution!

**Comment by mikias-abiy** [comment]
okay man thank for your time. May be we'll fix it some other time.

**Pull request merged**
